os: linux
language: ruby 
script:
- echo $TRAVIS_BRANCH
- echo $TRAVIS_JOB_ID
- echo $TRAVIS_JOB_NUMBER
- git log -1 --pretty=oneline
before_deploy:
- bash build.sh
deploy:
  provider: releases
#  api_key:
#    secure: XXXX
  file_glob: true
  file: koha-plugin-rest-biblios*.kpz
  skip_cleanup: true
  on:
    repo: NatLibFi/koha-plugin-rest-biblios
    branch: master
    tags: true
